"use client";

import { FormEvent, useMemo, useState } from "react";
import "./demo.css";

type Role = "OWNER" | "OPERATOR";
type Job = { id: string; motor: string; work: string; price: number; customer: string; status: "IN_PROGRESS" | "CLOSED"; date: string };
type Expense = { id: string; item: string; amount: number; date: string };
const initialJobs: Job[] = [
  { id: "JOB-DEMO-001", motor: "Honda Beat", work: "Ganti kulit jok dan tambah busa", price: 250000, customer: "Budi", status: "IN_PROGRESS", date: "11 Sep 2026" },
  { id: "JOB-DEMO-002", motor: "Yamaha NMAX", work: "Ganti kulit MB Tech", price: 350000, customer: "Rina", status: "CLOSED", date: "10 Sep 2026" },
  { id: "JOB-DEMO-003", motor: "Honda Vario", work: "Jasa pasang kulit", price: 120000, customer: "", status: "CLOSED", date: "09 Sep 2026" },
];
const initialExpenses: Expense[] = [{ id: "EXP-DEMO-001", item: "Belanja busa", amount: 200000, date: "11 Sep 2026" }];
const money = (n: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(n);

export default function DemoPage() {
  const [logged, setLogged] = useState(false), [role, setRole] = useState<Role>("OWNER"), [tab, setTab] = useState("home");
  const [jobs, setJobs] = useState(initialJobs), [expenses, setExpenses] = useState(initialExpenses), [notice, setNotice] = useState("");
  const [jobForm, setJobForm] = useState({ motor: "", work: "", price: "", customer: "" });
  const [expenseForm, setExpenseForm] = useState({ item: "", amount: "" });
  const active = jobs.filter((j) => j.status === "IN_PROGRESS"), closed = jobs.filter((j) => j.status === "CLOSED");
  const income = closed.reduce((s, j) => s + j.price, 0), out = expenses.reduce((s, e) => s + e.amount, 0);
  const title = useMemo(() => role === "OWNER" ? "Beranda Owner" : "Job Aktif", [role]);
  if (!logged) return <main className="login-screen"><div className="login-card"><div className="brand-mark">M</div><p className="kicker">MOTOKRAF · DEMO LOKAL</p><h1>Operasional Bengkel</h1><p className="muted">Prototype mobile untuk melihat alur aplikasi.</p><label>Username<select id="user"><option>Owner</option><option>Operator</option></select></label><label>PIN<input inputMode="numeric" placeholder="Masukkan PIN demo" /></label><button onClick={() => setLogged(true)}>Masuk ke Demo</button><small className="muted">Data di halaman ini sintetis dan tidak terhubung ke Google Sheets.</small></div></main>;
  function addJob(e: FormEvent) { e.preventDefault(); if (!jobForm.motor || !jobForm.work || !jobForm.price) return setNotice("Isi model motor, pekerjaan, dan harga deal."); setJobs([{ id: `JOB-DEMO-${String(jobs.length + 1).padStart(3, "0")}`, motor: jobForm.motor, work: jobForm.work, price: Number(jobForm.price), customer: jobForm.customer, status: "IN_PROGRESS", date: "11 Sep 2026" }, ...jobs]); setJobForm({ motor: "", work: "", price: "", customer: "" }); setNotice("Job demo berhasil ditambahkan."); setTab("jobs"); }
  function addExpense(e: FormEvent) { e.preventDefault(); if (!expenseForm.item || !expenseForm.amount) return setNotice("Isi keperluan dan total pengeluaran."); setExpenses([{ id: `EXP-DEMO-${String(expenses.length + 1).padStart(3, "0")}`, item: expenseForm.item, amount: Number(expenseForm.amount), date: "11 Sep 2026" }, ...expenses]); setExpenseForm({ item: "", amount: "" }); setNotice("Pengeluaran demo berhasil ditambahkan."); }
  function closeJob(id: string) { setJobs(jobs.map((j) => j.id === id ? { ...j, status: "CLOSED" } : j)); setNotice("Payment demo dicatat. Job menjadi CLOSED."); }
  return <main className="app-shell"><header className="app-header"><div><p className="kicker">MOTOKRAF · {role}</p><h1>{title}</h1></div><button className="ghost" onClick={() => setLogged(false)}>Logout</button></header>{notice && <div className="notice">{notice}<button onClick={() => setNotice("")}>Tutup</button></div>}<nav className="top-nav">{(role === "OWNER" ? [["home", "Beranda"], ["jobs", "Job"], ["history", "Riwayat"], ["more", "Lainnya"]] : [["jobs", "Job Aktif"], ["new", "Tambah Job"], ["more", "Menu"]]).map(([key, label]) => <button key={key} className={tab === key ? "selected" : ""} onClick={() => setTab(key)}>{label}</button>)}</nav>
    {tab === "home" && role === "OWNER" && <><section className="hero"><div><span className="live-dot" /> Terhubung ke Demo Lokal</div><h2>Ringkasan hari ini</h2><p className="muted">Pekerjaan aktif tetap menjadi prioritas.</p></section><section className="metrics"><Metric label="Job Aktif" value={String(active.length)} /><Metric label="Pemasukan Bulan Ini" value={money(income)} /><Metric label="Pengeluaran Bulan Ini" value={money(out)} /><Metric label="Selisih" value={money(income - out)} /></section><JobList jobs={active} onClose={closeJob} /></>}
    {tab === "jobs" && <><section className="section-head"><div><p className="kicker">PEKERJAAN</p><h2>{role === "OWNER" ? "Semua Job Aktif" : "Job Aktif"}</h2></div><button onClick={() => setTab("new")}>+ Tambah Job</button></section><JobList jobs={active} onClose={closeJob} /></>}
    {tab === "new" && <section className="panel form-panel"><p className="kicker">PEKERJAAN BARU</p><h2>Catat Job</h2><form onSubmit={addJob}><label>Model motor *<input value={jobForm.motor} onChange={e => setJobForm({ ...jobForm, motor: e.target.value })} placeholder="Contoh: Honda Beat / Yamaha NMAX" /></label><label>Deskripsi pekerjaan *<textarea value={jobForm.work} onChange={e => setJobForm({ ...jobForm, work: e.target.value })} placeholder="Contoh: Ganti kulit jok dan tambah busa" /></label><label>Harga deal (Rp) *<input type="number" inputMode="numeric" value={jobForm.price} onChange={e => setJobForm({ ...jobForm, price: e.target.value })} placeholder="Contoh: 250000" /></label><label>Nama pelanggan<input value={jobForm.customer} onChange={e => setJobForm({ ...jobForm, customer: e.target.value })} placeholder="Contoh: Budi" /></label><button>Simpan Job</button></form></section>}
    {tab === "history" && role === "OWNER" && <section className="panel"><p className="kicker">RIWAYAT</p><h2>Job CLOSED</h2><JobList jobs={closed} onClose={closeJob} /></section>}
    {tab === "more" && role === "OWNER" && <><section className="panel"><p className="kicker">UANG KELUAR</p><h2>Pengeluaran</h2><form onSubmit={addExpense}><label>Keperluan / item *<input value={expenseForm.item} onChange={e => setExpenseForm({ ...expenseForm, item: e.target.value })} placeholder="Contoh: Belanja busa" /></label><label>Total (Rp) *<input type="number" inputMode="numeric" value={expenseForm.amount} onChange={e => setExpenseForm({ ...expenseForm, amount: e.target.value })} placeholder="Contoh: 85000" /></label><button>Simpan Pengeluaran</button></form>{expenses.map(e => <div className="row" key={e.id}><span><b>{e.item}</b><small>{e.date}</small></span><b>{money(e.amount)}</b></div>)}</section><section className="panel"><p className="kicker">AKUN</p><h2>Mode aplikasi</h2><p className="muted">Demo Owner dapat berpindah ke Mode Kerja Operator.</p><button onClick={() => { setRole("OPERATOR"); setTab("jobs"); }}>Gunakan Mode Operator</button></section></>}
    {tab === "more" && role === "OPERATOR" && <section className="panel"><p className="kicker">MENU</p><h2>Mode Operator</h2><p className="muted">Fokus pada Job Aktif, Tambah Job, Media, dan Payment.</p><button onClick={() => { setRole("OWNER"); setTab("home"); }}>Kembali ke Mode Owner</button></section>}
    <footer className="demo-footer"><span>Demo lokal · data sintetis</span><button className="ghost" onClick={() => { setJobs(initialJobs); setExpenses(initialExpenses); setNotice("Data demo direset."); }}>Reset Demo</button></footer></main>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><small>{label}</small><strong>{value}</strong></div>; }
function JobList({ jobs, onClose }: { jobs: Job[]; onClose: (id: string) => void }) { return <section className="panel"><div className="section-head"><div><p className="kicker">DAFTAR</p><h2>Job {jobs[0]?.status === "CLOSED" ? "Selesai" : "Aktif"}</h2></div><strong>{jobs.length}</strong></div>{jobs.length ? jobs.map(j => <article className="job-card" key={j.id}><div><b>{j.motor}</b><span className="status">{j.status === "CLOSED" ? "CLOSED" : "IN PROGRESS"}</span><p>{j.work}</p><small>{j.customer || "Tanpa nama customer"} · {j.date}</small></div><div className="job-side"><b>{money(j.price)}</b>{j.status === "IN_PROGRESS" && <button onClick={() => onClose(j.id)}>Payment</button>}</div></article>) : <p className="empty">Belum ada Job.</p>}</section>; }
